### ISSUE TITLE
Half/Full trickle breaks Firefox or Safari, but Chrome works either

### ISSUE THREAD

**Issue by RobertLowe** [meetecho/janus-gateway#1169]
Related topic: https://groups.google.com/forum/#!searchin/meetecho-janus/firefox|sort:date/meetecho-janus/3PiHZ2mIs5I/CxI_ehzECgAJ

Quoting: Rhythm Chopra
> On further digging, I found that somehow a valid SDP session negotition can't be done by Firefox, because answer created for SDP offer by `RTCPeerConnection.createAnswer()` in `janus.js` contains an attribute `rtpmap: 120 VP8/90000`, where as the one created by Chrome has `rtpmap: 126 H264/90000`, which makes the Chrome for negotiate a valid session and prevents Firefox to do the same because my actual stream is `H264/90000` encoded. 
And Gstreamer Live stream on your demo website is VP8 encoded, so Firefox and Chrome both can play the stream due to valid answer created by both browser. But same is not the case with H264 encoded stream.
Please suggest how can I create a valid answer for SDP offer in Firefox, or is there any other workaround for this?

I've noticed strangely with h264 encoded `full_trickle` breaks Firefox with `ICE failed, add a TURN server and see about:webrtc for more details`, however when I disable `full_trickle` Firefox is able to play h264 but in doing so Safari is broken. Chrome works with full_trickle on or off. Firefox does play well with VP8 however. 

Is this a legitimate issue with the streaming plugin or browsers, or probably my configuration. I essentially copied the `streamingtest.js` into my app. Sorry, I know this should probably be posted on the forums, but it seems like more of an issue or at least some unknown behaviour to document?

I'm considering as a work around to run two instances and two upstreams for janus but that feels incorrect and wouldn't be applicable if I was using the videoroom plugin. I'd like to locate the root cause. I've seen minor difference in the SDPs but I'm not exactly sure where to begin to resolve them with `janus.js`, it feels like this should be handled?

**Comment by RobertLowe** [comment]
Follow up, running two instances of Janus, like a primary and secondary (one half, one full), happy to report Chrome, Firefox and Safari works. Feels good, so many days debugging and learning. 👍

**Comment by lminiero** [comment]
Sorry, missed this apparently: does your second message mean this was resolved?

**Comment by RobertLowe** [comment]
@lminiero not really resolved, but implemented a work around, but the cost is running two instances of Janus and burning twice the CPU receiving and increasing application complexity to some degree.

Thanks for the reply

**Comment by atoppi** [comment]
@RobertLowe tested with a recent Janus master, streaming demo and `ffmpeg` pipeline.
h.264 mountpoint works with `full_trickle = true` on Chrome 65, Firefox 58 and Safari.
h.264 mountpoint works with `full_trickle = false` on Chrome 65, Firefox 58 and Safari.

**WARNING**: In order to make Safari gather local candidates I added a call to `getUserMedia` (useless for streaming demo, but this is a Apple security policy I think).

The SDP answer containing a different video codec could suggest a misconfiguration somewhere.
How could Firefox answer with VP8 when H264 has been proposed in first place?
And even if that was the case, I would not expect an error on ICE setup, but rather an error on negotiation or a successful setup with a unplayable video.

**Comment by RobertLowe** [comment]
@atoppi interesting that `getUserMedia` is necessary. For all my tests SDPs showed matching codecs, I tested VP8 separately.

**Comment by lminiero** [comment]
Closing as it looks like we can't replicate this issue, and full-trickle seems to work as expected in all scenarios. Feel free to reopen if you can provide more data to support a potential issue.
