### ISSUE TITLE
janus_videoroom "unpublished" events dropped when tab is closed

### ISSUE THREAD

**Issue by s-ol** [meetecho/janus-gateway#1172]
I'm getting to grips with the Janus eventhandler API and am noticing that the `unpublished` events don't come through when the tab is closed and the handle and published expire at the same time.
Janus throws this error:

    [Mon Mar 12 14:03:41 2018] [ERR] [ice.c:janus_plugin_session_is_alive:401] Invalid plugin session (0x7f2710015a00)

This obviously comes from [janus.c:3160](https://github.com/meetecho/janus-gateway/blob/master/janus.c#L3160):

        if(plugin_session != NULL) {
		if((plugin_session < (janus_plugin_session *)0x1000) || !janus_plugin_session_is_alive(plugin_session) || plugin_session->stopped) {

it seems that in a sort of race condition the handle is invalidated before the publisher is removed and the event notification errors because of this.

is there an easy fix or is there a structural problem behind this? it seems pretty important to me to be able to depend on the consistency of this event.

**Comment by lminiero** [comment]
If there's no handle to send the event on, there's no way around that error: and this is always going to happen if you close a tab, as that will result in the handle to be detached before any meaningful API message can be sent to the plugin instead. You may want to play with the unbeforeunload to see if you can make sure messages are sent properly before closing the session.

Anyway, it depends what handle you're talking about here: if it's the publishers's handle, no big deal, the other participants will be notified anyway on their handles instead. When that doesn't happen because the plugin hasn't been notified about a detach (e.g., no explicit detach or destroy got to Janus after a tab close), session timeouts will notifiy about the user going away anyway, even if after some seconds and not right away.

**Comment by s-ol** [comment]
@lminiero: the event gets through to listeners properly, but it doesn't reach any event handlers. Yes, the tab is closed and therefore no more communication will happen, but the event **does** reach all the way to [janus_videoroom.c:3578](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L3578) where it *could* be sent to event listeners, but instead errors out, which seems to me to be mostly a bug.

**Comment by s-ol** [comment]
If I'm not wrong then this is the only event where I could do cleanup work, so if I want to attach my external API using event handlers it's important that I can be guaranteed not to miss this.

**Comment by lminiero** [comment]
Oh you meant event _handlers_: I thought you meant events on the user's side of the API. You can try changing the `if` to

    if(participant && gateway->events_is_enabled()) {

and the `participant->room->room_id` part to

    json_integer(participant->room_id)

We recently made the integer `room_id` property part of the participant object itself exactly to address a similar issue in another part of the code (and potential crashes that could happen there when `participant->room` was being invalidated). If that works, we can change it in the repo too.

**Comment by lminiero** [comment]
Nevermind that... got your point now. It's in the core that it stops, not the plugin. I'll have to think about this.

**Comment by s-ol** [comment]
@lminiero I did, but that is not the check that is failing; the event goes through to `janus_plugin_notify_event` and errors out in `janus_plugin_session_is_alive` (see original comment)

**Comment by lminiero** [comment]
Looks like the only solution is passing `NULL` instead of `handle` in the `gateway->notify_event` call you mentioned. The checks in the core are needed because the handle pointer may be invalid, and trying to access its property may get the whole instance to crash.

Have you checked if it's an issue in the refcount branch, which we'll merge soon?

**Comment by lminiero** [comment]
As a side note, in event handlers you get a ton of other events for the handle too. If you see a `detached` for the handle that was associated to a specific publisher, that can act as your "unpublished" too, as you know the user is definitely not publishing anything anymore on that handle. Relying on "unpublished" alone is indeed not a good idea.

**Comment by atoppi** [comment]
If you are using vanilla `janus.js`, you are sending a synchronous `destroy` session request in the `onbeforeunload` callback. That is handled into the core [here](https://github.com/meetecho/janus-gateway/blob/master/janus.c#L894), then `janus_ice_handle_destroy` is called [here](https://github.com/meetecho/janus-gateway/blob/master/janus.c#L444), and finally the plugin session gets invalidated in the early steps [here](https://github.com/meetecho/janus-gateway/blob/master/ice.c#L1056).
Any subsequent reference to this plugin session will trigger the mentioned error `Invalid plugin session`.

**Comment by s-ol** [comment]
@lminiero I'm trying the refcount branch now but something is wrong, it starts out working fine but after I join the room initially the webSockets API stalls and becomes unresponsive (both existing connection from my backend and all future connections don't receive any responses and time out)

**Comment by s-ol** [comment]
@atoppi I overwrote `onbeforeunload` in the browser console and the same behaviour and error happens, so this seems to be related rather to the way webRTC hangups are handled than to how janus.js or other clients handle leaving (which is great because that seems more dependable)

**Comment by lminiero** [comment]
> @lminiero I'm trying the refcount branch now but something is wrong, it starts out working fine but after I join the room initially the webSockets API stalls and becomes unresponsive (both existing connection from my backend and all future connections don't receive any responses and time out)

Can't seem to replicate this issue, it works just fine for me. If you can provide details, please open a new issue though (let's not mix things here).

**Comment by lminiero** [comment]
PS: make sure you compile libwebsockets as documented in the README, as otherwise the deadlock is a well known issue that we [solved already](https://github.com/meetecho/janus-gateway/issues/732).

**Comment by lminiero** [comment]
Any update?

**Comment by s-ol** [comment]
@lminiero I haven't tried the refcounting branch again yet, but for now i am relying on the 'handle detached' event as you also proposed.

**Comment by lminiero** [comment]
@s-ol have you tried again with master? (which is now refcount, as we merged that in the meanwhile).

**Comment by s-ol** [comment]
sorry for the delay, I finally got around to try `master` again, what should have been the same build steps works now.
I'm still seeing the error in a very basic test where two clients join a videoroom, then one refreshes the page abruptly.

**Comment by lminiero** [comment]
Sorry, I'm confused: is it working or not? If not, what doesn't? Are we talking of the same issue you reported initially? We mixed several things, here.

**Comment by s-ol** [comment]
Ah, I could've been more clear. The crash etc. are gone, building, running etc is all working fine.
However the error I reported initially persists and I regularly see logs like

    [Mon Mar 12 14:03:41 2018] [ERR] [ice.c:janus_plugin_session_is_alive:401] Invalid plugin session (0x7f2710015a00)

on a fresh (yesterday) build from `master`.
The scenario for reproducing is as mentioned above, simply two clients in a videoroom (using janus.js) with an abrupt disconnect (by refreshing).

**Comment by lminiero** [comment]
The above commit fixes it for me. Please let me know if that's not the case.
