### ISSUE TITLE
Janus.js client does not seem to work in Firefox 60

### ISSUE THREAD

**Issue by JoshLipps** [meetecho/janus-gateway#1235]
**OS:** macOS 10.13.4
**Browser:** Firefox 60.0 (64-bit)
**Janus Version:** 0.3.1
**Description:** When Web RTC steam starts, stream seems to connect, but no video is displayed. 

[console.log debug output](https://pastebin.com/raw/zkRw9nxh)
This Demo site seems to fail in a similar way: 
https://janus.conf.meetecho.com/streamingtest.html
![image](https://user-images.githubusercontent.com/779444/40043195-bbcf655a-585e-11e8-913b-cab0354dc19a.png)

I hope this helps. Thanks for the great software.

**Comment by lminiero** [comment]
Use the janus.js from master, we fixed several things lately. Works just give for me in all versions of Firefox. Closing.

**Comment by JoshLipps** [comment]
I have tried the Janus.js from master as well and still face the same issue. 
It does still work in Chrome and Safari, so I though It was due to the recent FF update, but I'll keep investigating. Thanks for checking.
