### ISSUE TITLE
pp-rec segment fault with h264

### ISSUE THREAD

**Issue by 3nk** [meetecho/janus-gateway#1393]
Hi,
First of all thanks for your great work on janus !

My application works fine with janus (recordplay) over almost all browsers (Firefox, Chrome, Edge) 
but on Safari since v12 when i try to process the generated MJR video file, the result is:

```
/opt/janus/bin/janus-pp-rec /opt/janus/share/janus/recordings/rec-1538557294902-video.mjr /opt/janus/share/janus/recordings/rec-1538557294902-video.mp4
Janus version: 45 (0.4.5)
Janus commit: 319a67308925e5258ed7032281ccf1d082a642e1
Compiled on:  Tue Oct  2 14:14:23 UTC 2018

/opt/janus/share/janus/recordings/rec-1538557294902-video.mjr --> /opt/janus/share/janus/recordings/rec-1538557294902-video.mp4
File is 706206 bytes
Pre-parsing file to generate ordered index...
[WARN] New .mjr header format
This is a video recording:
  -- Codec:   h264
  -- Created: 1538557294920720
  -- Written: 1538557296669300
SSRC detected: 4173138992
Counted 861 RTP packets
Counted 861 frame packets
[WARN] Profile is not baseline (100 != 66)
[WARN] Profile is not baseline (100 != 66)
  -- 32x16 (fps [90,17280] ~ 1000)
First keyframe: 0
First keyframe: 0
First keyframe: 0
First keyframe: 0
Segmentation fault

```

And sometimes:

```
/opt/janus/bin/janus-pp-rec /opt/janus/share/janus/recordings/rec-1538557294902-video.mjr /opt/janus/share/janus/recordings/rec-1538557294902-video.mp4
Janus version: 45 (0.4.5)
Janus commit: 319a67308925e5258ed7032281ccf1d082a642e1
Compiled on:  Tue Oct  2 14:14:23 UTC 2018

/opt/janus/share/janus/recordings/rec-1538557294902-video.mjr --> /opt/janus/share/janus/recordings/rec-1538557294902-video.mp4
File is 706206 bytes
Pre-parsing file to generate ordered index...
[WARN] New .mjr header format
This is a video recording:
  -- Codec:   h264
  -- Created: 1538557294920720
  -- Written: 1538557296669300
SSRC detected: 4173138992
Counted 861 RTP packets
Counted 861 frame packets
[WARN] Profile is not baseline (100 != 66)
[WARN] Profile is not baseline (100 != 66)
  -- 32x16 (fps [90,17280] ~ 1000)
First keyframe: 0
First keyframe: 0
First keyframe: 0
First keyframe: 0
First keyframe: 6570
*** Error in `/opt/janus/bin/janus-pp-rec': double free or corruption (!prev): 0x000000000249e460 ***
Aborted

```

Do you have any suggestion ?

**Comment by lminiero** [comment]
Have you tried master already? We fixed something in the post-processor just a couple of days ago.

**Comment by 3nk** [comment]
Hi @lminiero 

Thanks for the message, i just tried with the master and the issue is still the same.

**Comment by atoppi** [comment]
@3nk can you share a sample mjr that triggers the crash?

**Comment by 3nk** [comment]
@atoppi sure, here you go

[rec-1538564974101-video.zip](https://github.com/meetecho/janus-gateway/files/2441759/rec-1538564974101-video.zip)

**Comment by 3nk** [comment]
We've just tried a safari 11.4 on ios and everything works as expected, looks like the issue is only with Safari 12.

**Comment by lminiero** [comment]
It looks like the problem is in the resolution we extract from the keyframe:

```
[WARN] Profile is not baseline (100 != 66)
  -- 32x16 (fps [90,17280] ~ 1000)
```

Clearly the video is not 32x16 (probably more a 640x480), but since we use that resolution to calculate the buffer to allocate for frames to save, we overflow as `32*16*3` is too small. No idea why the H.264 Safari generates gives us a broken resolution when we parse the SPS: it might be a one-time issue, or something that happens regularly (is this happening for all video recordings from Safari?).

**Comment by 3nk** [comment]
@lminiero it happens everytime with safari 12.

**Comment by lminiero** [comment]
Ok, one more reason to hate Apple then :wink: 
As I said, no idea why their SPS is different, or if it's the SPS parsing that is incorrect for the profile they use (which should be 66 "Baseline as per the standard, but is 100 "High" instead). I don't plan to investigate this parsing further, as I don't care much about proprietary formats. What I'll do is using a different, and larger, width/height when we parse an unexpectedly low value: that should fix the overflow issue.

**Comment by lminiero** [comment]
Please test with this new patch.

**Comment by lminiero** [comment]
@3nk, just FYI, we confirmed the SPS parsing is different when using higher profiles, and added some more code to the postprocessor: https://github.com/meetecho/janus-gateway/commit/6bfba40bf0909b1e06cff34bdb758292858d7261

**Comment by 3nk** [comment]
@lminiero everything looks fine we the new commit !

Thanks again :)
