### ISSUE TITLE
Echotest Plugin - Data Channel does not Establish Consistently

### ISSUE THREAD

**Issue by MichaelB76** [meetecho/janus-gateway#144]
When testing the echotest plugin I've noticed that the Data Channel does not always connect. When it fails I get the following error about a minute later:

*[ERR] [../sctp.c:janus_sctp_association_setup:276:] [380796227] Error connecting to SCTP server at port 5000*

Looking at the code it's failing in sctp.c line 275, on janus_sctp_association_setup(). The call to usrsctp_connect() returns an error code after a long timeout. Here's a paste of the log output for the failed connection:

http://pastebin.com/XDbMNHZh

I haven't been able to establish a pattern to the failure I'm afraid, it just seems to happen randomly including on the first call made after starting Janus. Please let me know if there is anything else I can do to help diagnose this.

**Comment by lminiero** [comment]
Please provide a log with debug 5, the log you pasted doesn't have enough information. My guess is that there's something wrong with the DTLS communication, which acts as the actual transport for SCTP messages. In fact, the port you see mentioned there is purely virtual (both peers negotiate 5000), and as long as DTLS/SCTP messages are being exchanged it should work fine.

Is this happening with Chrome or Firefox?

**Comment by MichaelB76** [comment]
I'm getting this with Firefox. I've set the debug level to 5 and will post a log this afternoon.

**Comment by MichaelB76** [comment]
Here's the new log, I've snipped it at the beginning of the new call. Hope it's useful, please let me know if there is anything else you want.

http://pastebin.com/2Budw33P

**Comment by lminiero** [comment]
From what I can see, the SCTP stack in Janus is trying to send a 100 bytes message through DTLS over an dover, and eventually gives up with a 56 bytes message which is probably something that gives up. You should check with Wireshark whether these DTLS messages are actually being sent, and/or if they're getting to the other side. In one of the next versions I'll also add some SCTP-related debug to check the exact SCTP messaging involved, as DTLS encrypts that. You can in part already look into this if you add a ```#define DEBUG_SCTP``` before ```#ifdef DEBUG_SCTP``` in sctp.c, which will redirect unencrypted SCTP messages to port 10000 and 20000 for inspection.

**Comment by MichaelB76** [comment]
OK thanks, I'll check using Wireshark.

**Comment by lminiero** [comment]
Any news?

**Comment by MichaelB76** [comment]
Sorry for the delay, I've had some other things to look at. I've just got back to looking at it today, I can reproduce it using Firefox but not Chrome. When using Firefox I can see the 100 byte messages are reaching the client PC but I'm not sure if Firefox is reading them, I'm trying to work out how to find that out.

**Comment by lminiero** [comment]
Have you tried with the latest version to see if it works now? We fixed some SCTP related code recently.

**Comment by MichaelB76** [comment]
Hi, I got the latest Janus source about a week ago and still have the problem, so I'm not sure if I have the relevant changes. Is there a particular commit you'd like me to test against?

I spent some more time looking at this without much success. I used the DEBUG_SCTP test streams as you suggested but it wasn't very enlightening, the messages are in binary format. I'd guess it's some kind of handshake which isn't being performed correctly.

I've also found that it's possible to crash Janus with this problem. The call to usrsctp_connect() does not return for at least a minute, I guess until it finally gives up. If I close the call in the meantime and make some new ones it can crash when usrsctp_connect() finally returns. I'll sort out a backtrace for this.

**Comment by lminiero** [comment]
When you enable DEBUG_SCTP, it creates a txt file for the session that can then be converted to a pcapng dump and opened in Wireshark (see documentation). That should allow you to check whether or not the two peers are actually "talking" SCTP or not. A timeout in Janus probably means the peer never answers. Unfortunately I haven't been able to replicate this so far. Is this happening consistently for you?

Thanks for the heads-up about the crash. I'll look into this as well.

**Comment by MichaelB76** [comment]
OK thanks, I'll get that change and give it a try.

It doesn't happen every time but I can reproduce it without too much difficulty. It could be timing related perhaps, my Janus is compiled without optimizations for debugging which would slow it down. I still haven't seen the problem with Chrome but that could just be timing.

**Comment by MichaelB76** [comment]
Hi, I followed the new instructions in the new version of sctp.c and I have a couple of pcap files. When it fails the message sequence looks like this:

Inbound INIT from Web Client
Outbound ABORT from Janus
Outbound INIT from Janus (repeated periodically, with no response from Web Client)

Here's a paste to the text file: http://pastebin.com/szj9cfZt

When the data channel establishes there is no ABORT message before the outbound INIT is sent.

Here's the full message sequence when it succeeds: http://pastebin.com/aij6mcyM

Looks like the ABORT message is causing the problem. It's odd that Janus continues with an INIT message immediately after sending the ABORT. None of this is in the Janus code itself so it could be a problem with the usrsctp library, or possibly Janus could be corrupting some memory used by that library. Or it could be a data dependant bug triggered by something in the INIT from Firefox.

Please let me know if there is anything else I can do. I'm not seeing this problem when using Chrome but it's possible that it ignores any ABORT messages, I could check this if it is useful.

**Comment by MichaelB76** [comment]
Hi, I have a bit more info on this problem. I'm now seeing it with Chrome regularly as well, although the behaviour is a little different. Here's the message sequence when it fails with Chrome:

http://pastebin.com/gqBZatL4

There is an inbound INIT from the web client followed by an outbound ABORT from Janus. Then an outbound INIT is sent from JANUS followed by an inbound ABORT from the web client.

There is a difference in behaviour between Firefox and Chrome which explains why we thought it was working reliably with Chrome. In our webpage we have handling for the ondataopen callback in janus.js. When using Firefox ondataopen is never call so we know the data channel isn't established. With Chrome ondataopen is called so we think it is connected until we try to use it, getting the following error in the JavaScript console:

Uncaught InvalidStateError: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'

This is anecdotal, but Chrome seems to be much more unreliable recently (perhaps 20% of connection attempts are failing), possibly because it has updated itself. Or possibly I didn't realise how often the datachannel was failing because of the issue above.

We've updated the usrsctp library to the latest version but this hasn't helped. I also spent some time looking at the INIT messages in the capture file but couldn't see any obvious differences between them in the success and failure cases.

Any suggestions would be welcome, I'm not sure what more can be done to diagnose or workaround this problem.

**Comment by lminiero** [comment]
Any hint on how to reproduce this? I haven't been able to do that so far.

**Comment by MichaelB76** [comment]
Hi, I've been away for Easter. I'm not sure what to suggest I'm afraid. Perhaps some difference in our setups is showing up the problem? What flavour of Linux are you using please? We've tried Fedora 20 and Centos 7, both running in VMs under Hyper-V.

**Comment by MichaelB76** [comment]
@lminiero - I've made a bit more progress investigating this. Using the WanEm network simulator I can make the problem go away by introducing about 100ms of latency, I've managed about 40 connections to EchoTest in a row. When I stopped routing through the network simulator it failed on the second attempt.

I'll play around with this some more to see how sensitive it is to latency.

**Comment by lminiero** [comment]
@MichaelB76 100ms of latency on what? if a lack of latency were the cause, wouldn't it always fail when tried on localhost? keep me posted!

**Comment by MichaelB76** [comment]
@lminiero - 100ms of latency between my VM running Janus and the hosting PC running the browser. Good point about localhost, I'll running EchoTest from a browser inside the VM and see what happens. If I reduce the latency to 10ms I do get the problem, so it does appear to be timing related rather than something to do with network comms directly between the VM and hosting PC.

**Comment by MichaelB76** [comment]
It took a few tries, but I have got it to fail when running FireFox within the VM hosting Janus.

**Comment by lminiero** [comment]
Are you getting the same results when trying with the EchoTest on our demo site? Just trying to figure out if this  can be isolated to the VM itself. If it is timing related, it may be caused by the machine being a bit too slow, and so could be reproduced by launching, e.g., Janus via valgrind.

**Comment by MichaelB76** [comment]
I can't reproduce the problem with your demo page. Yes, the performance of the VM or the virtual network driver could affect the timing so that threads are scheduled in a different order. Given the intermittent nature of the problem I think that's quite likely.

**Comment by lminiero** [comment]
I've given this some thought, and I think it may be caused by the SCTP stack in Janus not being ready yet when the message is received. This might trigger the ABORT, I guess (I'm not very familiar with SCTP, not sure what may cause that), and might also explain the timing related fixes you noticed, as 100ms later all should be ready.

IIRC we already have some code in place to fence that, but that may not be enough. I'll check if that's indeed the case.

**Comment by lminiero** [comment]
We do have such checks in place, as I thought: the messages (both incoming and outgoing) are all enqueued, and none of them are handled before the stack is indeed ready. Since a couple of threads are involved, though, I added a further check to avoid writing data until the SCTP association setup has been actually started. Let me know if you notice any improvement with this fix.

**Comment by MichaelB76** [comment]
Thanks for that, I've tested the fix and the datachannel is connecting much more reliably for me now. I managed 30 or 40 successful connections in a row, with no failures.

However, I don't think the fix is entirely safe. If another thread is scheduled between sctp->ready being set to TRUE and usersctp_connect() being called (or perhaps running to a critical point within that function) it could still fail. To test this I tried adding a g_usleep(1) between the two statements, allowing another thread to be scheduled, and had the problem again. In a production environment I'd expect it to fail occasionally, just depending on when the threads are scheduled.

When it fails an incoming message is processed before usrsctp_connect() is called, probably because usrsctp_conninput() is being called concurrently. I'm wondering if usrsctp_connect should be called from the same thread to prevent this from happening?

**Comment by lminiero** [comment]
Unfortunately I cannot set the flag *after* usrsctp_connect, as usrsctp_connect is blocking. I'll check what can be done with respect to that.

**Comment by lminiero** [comment]
That said, usrsctp_conninput can never be called concurrently: for a specific SCTP association, only its incoming/outgoing thread can issue a usrsctp_conninput call, and only that same thread can receive data from the SCTP stack to relay on the network via DTLS. This means that a usrsctp_connect call does nothing as well except until the incoming/outgoing thread starts, except queueing the message for delivery.

**Comment by MichaelB76** [comment]
I can confirm that setting the ready flag after the call to usrsctp_connect() doesn't work, the connection fails every time. Experimenting a bit more the connection fails if usrsctp_conninput() is called before usrsctp_connect(). As you say, usrsctp_connect() blocks, but it appears to only unblock once usrsctp_conninput() is called. 

It's good that we've made some progress on this and your fix is a big improvement, but I can't see how to make this work completely reliably, given that the other thread could be scheduled immediately after the sctp->ready flag is set. I'm not sure if this is a weakness in the usrsctp library or if there is something else we could do.

**Comment by lminiero** [comment]
If that's the issue, one way to handle this is to never call usrsctp_conninput before data has been sent, which is something I can handle via an ad-hoc variable in janus_sctp_thread. I'll try and craft a quick hack to test this for you to check today.

**Comment by MichaelB76** [comment]
Thanks, I'll test this out when it's available.

**Comment by lminiero** [comment]
It already is, see above.

**Comment by MichaelB76** [comment]
I've tested the new fix and it seems to work fine with both FireFox and Chrome. I believe this supersedes the previous fix with the sctp->ready flag so I removed it before testing.

**Comment by lminiero** [comment]
Ok, I'll remove the ready flag and close the session then.
