### ISSUE TITLE
janus sending local ip in connection information (webrtc to sip call) even though nat_1_1_mapping ip available when janus behind NAT.

### ISSUE THREAD

**Issue by DileepNunna** [meetecho/janus-gateway#1504]
Installed janus server behind NAT (aws server). while doing webrtc to sip call, janus sending local ip in sip invite sdp connection information. janus not receiving any media packets from sip side due to local ip in connection info. so where i have to give public ip to get effect in sdp.

**Comment by lminiero** [comment]
Please describe the issue in the text itself, not just the title: the issue text is still the placeholder we add ourselves.

Is the public IP missing where? In the SDP Janus sends to the browser? Or to the SIP endpoint? If it's the former it's a bug; if it's the latter it's not, since the SIP plugin is configured in a different way, and the nat-1-1 mapping has no effect on plugins, only the core.

**Comment by DileepNunna** [comment]
Installed janus server behind NAT (aws server).  while doing webrtc to sip call, janus sending local ip in sip invite sdp connection information. janus not receiving any media packets from sip side due to local ip in connection info. so where i have to give public ip to get effect in sdp.

**Comment by lminiero** [comment]
Yep, then as I said, the nat-1-1 mapping only applies to the core, so the SDP on the WebRTC side. To do the same on the SIP side would need a new configuration property in the SIP configuration instead.

Have you already tried setting the public IP in the `local_ip` property of `janus.plugin.sip.jcfg` or `janus.plugin.sip.cfg`?

**Comment by DileepNunna** [comment]
yes, i tried by setting the local_ip in janus.plugin.sip.cfg. but janus verifying is a valid ip address or not (is the ip in the interfaces list or not). getting error 'Error setting local IP address to 52.10.x.x, falling back to detecting IP address...'.

**Comment by lminiero** [comment]
Yeah, makes sense, that setting only constrains what we'll bind to, not what we'll put in the SDP. I'll take note of the fact that we need a new setting to set the public IP in the SIP plugin as well.

**Comment by lminiero** [comment]
This commit should fix it, see the new `sdp_ip` property you can set in the SIP configuration file: please let me now if that's not working for you. Please notice this only impacts the `c=` attributes in the SDP, and so only media, not signalling.

**Comment by StephaneG31** [comment]
We have the same type of problem, and with this fix is OK.
But we still have a problem with Contact header.
We try to use behind_nat=true but we are on a local private network will internet access only available through a forward proxy.
Maybe sdp_ip must also be apply to Contact header? Or maybe a new parameter can fix our problem?
