### ISSUE TITLE
Videoroom: rtp_forward api reports success but rtp doesn't start

### ISSUE THREAD

**Issue by mirkobrankovic** [meetecho/janus-gateway#2589]
Regarding this thread:
https://groups.google.com/g/meetecho-janus/c/xs6qCRRD874

Currently on master (and I tried going back in git log and got till version 0.9.5 since I needed to pull down other deps, libnice,...) I can't get the rtp flow after a success response to rtp_forward request.

Note: I tried it on multistream branch and seems to work correctly with no client/signaling changes, I see that multistream has been updated with master few times since, but i'm confused how I can get it to work on that branch.

It makes no difference if I forward Audio or video, both work on multistream branch and none on master, same as for ipv4/6 or different ports in request

**Comment by atoppi** [comment]
hi @mirkobrankovic,
you didn't mention that `master` was broken as well.
Regarding this aspect we use the videoroom / audiobridge rtp forwarding **A LOT** without any issue.
Could you try again by fetching the sources and building in a clean folder ?

**Comment by mirkobrankovic** [comment]
i did say "Currently on master ..." but sorry for unclear sentences :p 
Ok let me try in clean master

**Comment by atoppi** [comment]
I meant on the group, you only mentioned other branches AFAIR.

**Comment by mirkobrankovic** [comment]
aah yeah, i tested master in the mean time :) but they went to older releases to see where it broke for me, but got to 0.9.5 and because of libnice downgrade i stopped

**Comment by mirkobrankovic** [comment]
Tried now with clean master, also broken for me.
I'm now sending request for  localhost:30000 and getting ipv6 in reply:
```
      "rtp_stream" => %{
        "audio" => 30000,
        "audio_stream_id" => 3440531279,
        "host" => "::1"
      },
```
maybe related

**Comment by lminiero** [comment]
Maybe `::1` is the issue? Are you passing `localhost` to the host when creating the forwarder? What if you set `127.0.0.1`?

**Comment by atoppi** [comment]
Works as expected for me on latest master.
1) published audio-video inside a room 1234 and got pub id 371880835705219
2) requested the forwarding of the audio to 127.0.0.1:30000

**Request**
```
{
    "request": "rtp_forward",
    "host": "127.0.0.1",
    "room": 1234,
    "publisher_id": 371880835705219,
    "audio_port": 30000,
    "secret": "adminpwd"
}
```

**Response**
```
{
    "janus": "success",
    "transaction": "1aTSUppCxZFe",
    "response": {
        "publisher_id": 371880835705219,
        "rtp_stream": {
            "audio_stream_id": 3718720847,
            "audio": 30000,
            "host": "127.0.0.1"
        },
        "room": 1234,
        "videoroom": "rtp_forward"
    }
}
```

```
atoppi@atoppi:~/src/janus-gateway$ sudo ngrep -d any port 30000
interface: any
filter: ( port 30000 ) and (ip || ip6)
#
U 127.0.0.1:35089 -> 127.0.0.1:30000 #1
  .o.L...@..v.....1$......x....V...*...1....-......w.}.hL..r.{j.a...`ZK..]X.,S..C.KW.a....92.4.M..*
  .....5....r1.                                                                                    
#
U 127.0.0.1:35089 -> 127.0.0.1:30000 #2
  .o.M......v.....1$......x....)..1.Y..q.\.x...K..P)J.R]....M.1P..> ..`...r....^..o...HG...(....ow.
  a....E?I.....#                                                                                   
#
U 127.0.0.1:35089 -> 127.0.0.1:30000 #3
  .o.N.. ...v.....1$......x.7N4...u=~...e3."_.}}df...p...a..........."..i.Gm+..F0..;a.u6.'p...`..l.
#
U 127.0.0.1:35089 -> 127.0.0.1:30000 #4
  .o.O..$...v.....1$......x...T?O.H.?...w......H.1.....j.s..?.=....W...3K9.y.f.7....%K.V....LK}.j;.
  D                                                                                                
#
U 127.0.0.1:35089 -> 127.0.0.1:30000 #5
  .o.P..(@..v.....1$......x.y.....&.'.=..u\.y...Rq.a.!...{.5pD]..*x.<.6.....O.......:..&..MM..T..a 
#
U 127.0.0.1:35089 -> 127.0.0.1:30000 #6
  .o.Q..,...v.....1$......x..~$e..:..pF.r.G.....Eoh;.".Cs ..f...Je.?....d..~}....nf........@j....6.
  AE&..                                                                                            
#
```

**Comment by tmatth** [comment]
@mirkobrankovic as @lminiero pointed out, setting `host` may help, but also you may want to set `host_family`.

That said, there may be an issue with the host+family+socket combination Janus makes by default for RTP forwarders depending on your OS, networking etc. but that might be only exposed on certain setups.

**Comment by lminiero** [comment]
I just tried passing "localhost", which was resolved to "::1" in my case but still worked (RTP packets were forwarded as expected).

**Comment by mirkobrankovic** [comment]
I tried with 127.0.0.1, still the same.
Since it is working for you I guess the problem is on my side.

I see you set  `secret`, I don't set it, is it a mandatory field by default?

**Comment by mirkobrankovic** [comment]
What is confusing me the most is with changing only to multistream ( not changing environment, client code,...) It start to work. That i can't understand ;)

**Comment by mirkobrankovic** [comment]
So it is definitely related to the ip family somehow.
127.0.0.1 didn't work now for me on any branch.
localhost only on multistream branch,
and specific default gateway ip works on master also:
```
U 192.168.64.149:37360 -> 192.168.64.1:30000 #2950
  .o........}.........x....[..U.._weC..\....D.6.e.Vh.IL.....B...._....By}.Q[,.3....(@..zO;9}J.Bmu=`..
#
U 192.168.64.149:43300 -> 192.168.64.1:30000 #2951
  .o......m/..........x5,...yk.W..i...-8O......}dy.?]V/?......O.....3..o...^.r.|.....2.$A5a.L....9.  
#
```
So it is not a bug, I will close it :d

Thanks for great help

**Comment by mirkobrankovic** [comment]
Found out tht whole confusion was that I wasn't sending audio:true in configure request, probably some versions accepted it based on SDP by default and some newer one didn't and so my audio wasn't started like video :/

Works now perfectly :D thanks again
