### ISSUE TITLE
JANUS - 200 OK is not sent

### ISSUE THREAD

**Issue by clandolfa** [meetecho/janus-gateway#840]
Hi everyone
We encountered an issue regarding a sip call between our janus installation and asterisk. 

We analyze a sip trace between asterisk and janus gateway and we notice that the sip session miss the 200 OK message that janus should send after 180 Ringing message.

The janus log detect an error that i post right now (Couldn't update session details (missing or invalid remote IP address)

[Mon Apr  3 11:50:22 2017] This is involving a negotiation (answer) as well:
v=0^M
o=- 3376511722520956189 2 IN IP4 1.1.1.1^M
s=-^M
t=0 0^M
m=audio 9 RTP/SAVPF 0 101^M
c=IN IP4 1.1.1.1^M
a=sendrecv^M
a=rtpmap:0 PCMU/8000^M
a=rtpmap:101 telephone-event/8000^M

[Mon Apr  3 11:50:22 2017] Going to negotiate audio...
[Mon Apr  3 11:50:22 2017] Allocating audio ports:
[Mon Apr  3 11:50:22 2017] Audio RTP listener bound to port 54444
[Mon Apr  3 11:50:22 2017] Audio RTCP listener bound to port 54445
[Mon Apr  3 11:50:22 2017] Setting protocol to RTP/AVP
[Mon Apr  3 11:50:22 2017] [transports/janus_http.c:janus_http_request_completed:1706] Request completed, freeing data
[Mon Apr  3 11:50:22 2017] Detected audio codec: 0 (pcmu)
[Mon Apr  3 11:50:22 2017] Prepared SDP for 200 OK:
v=0^M
o=- 3376511722520956189 2 IN IP4 1.1.1.1^M
s=-^M
t=0 0^M
m=audio 54444 RTP/AVP 0 101^M
c=IN IP4 172.16.8.105^M
a=sendrecv^M
a=rtpmap:0 PCMU/8000^M
a=rtpmap:101 telephone-event/8000^M
[Mon Apr  3 11:50:22 2017] [6485146222212356] Sending event to transport...
[Mon Apr  3 11:50:22 2017] Sending event to janus.transport.http (0x7f8c38042ff0)
[Mon Apr  3 11:50:22 2017] Got a Janus API event to send (0x7f8c38042ff0)
[Mon Apr  3 11:50:22 2017]   >> Pushing event: 0 (Success)
[Mon Apr  3 11:50:22 2017] Starting relay thread (cc100 <--> sip:0000000000@172.16.8.20)
[Mon Apr  3 11:50:22 2017] Updating session sockets
[Mon Apr  3 11:50:22 2017] [ERR] [plugins/janus_sip.c:janus_sip_relay_thread:3329] [SIP-cc100] Couldn't update session details (missing or invalid remote IP address)
[Mon Apr  3 11:50:22 2017] [cc100][nua_i_state]: 200 OK

Could you help us to understand which is the error? 
Thanks in advance.

**Comment by lminiero** [comment]
It looks like you're using an outdated version of the SIP plugin, we fixed this weeks ago. Closing.

**Comment by dtagliavini** [comment]
Hi,

we have updated janus-gateway to the latest version (0.2.3) but we still have problem.

I have analyzed traffic on eth0 on asterisk with tcpdump, [here](https://drive.google.com/file/d/0ByoCiEOkL0PtMVdueE8tUXZpSU0/view?usp=sharing) you'll find an image with the traffic flow. 
I click on answer on the siptest.html demo page after popup appears but it's seems Janus it's starting to send RTP traffic without sending 200 OK.
